name: Deploy a Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy_hosting:
    name: Deploy Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy solo Hosting a Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: rubik-bolivia
          channelId: live

  deploy_functions:
    name: Deploy Functions
    runs-on: ubuntu-latest
    needs: deploy_hosting
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias de Functions
        run: npm install
        working-directory: functions

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Functions a Firebase
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project rubik-bolivia
        working-directory: .
